### Матрицы и матричные операции. Часть 1

In [2]:
import numpy as np

In [13]:
A = np.array([[1, 0], [2, 1], [1, 0], [2, 1]])
B = np.array([[[1, 0], [2, 1], [1, 0], [2, 1]]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[1 0]
 [2 1]
 [1 0]
 [2 1]]
Матрица B
[[[1 0]
  [2 1]
  [1 0]
  [2 1]]]


ValueError: shapes (4,2) and (1,4,2) not aligned: 2 (dim 1) != 4 (dim 1)

In [11]:
A = np.array([[1, 0, 4, 5, 3], [2, 1, 10, 5, 10]])
B = np.array([[2, 0, 4], [0, 0, 1], [2, 1, 9], [2, 0, 4], [0, 0, 1]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1  0  4  5  3]
 [ 2  1 10  5 10]]
Матрица B
[[2 0 4]
 [0 0 1]
 [2 1 9]
 [2 0 4]
 [0 0 1]]
Матрица AB
[[ 20   4  63]
 [ 34  10 129]]


In [15]:
A = np.array([[1, 0, 3], [2, 1, 4], [1, 0, 4], [2, 1, 5], [1, 0, 6], [2, 1, 3], [1, 0, 3], [2, 1, 1]])
B = np.array([[2, 0, 4, 0, 0, 1, 9, 3], [0, 0, 1, 2, 1, 9, 2, 0], [0, 0, 11, 2, 1, 9, 2, 0]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[1 0 3]
 [2 1 4]
 [1 0 4]
 [2 1 5]
 [1 0 6]
 [2 1 3]
 [1 0 3]
 [2 1 1]]
Матрица B
[[ 2  0  4  0  0  1  9  3]
 [ 0  0  1  2  1  9  2  0]
 [ 0  0 11  2  1  9  2  0]]
Матрица AB
[[ 2  0 37  6  3 28 15  3]
 [ 4  0 53 10  5 47 28  6]
 [ 2  0 48  8  4 37 17  3]
 [ 4  0 64 12  6 56 30  6]
 [ 2  0 70 12  6 55 21  3]
 [ 4  0 42  8  4 38 26  6]
 [ 2  0 37  6  3 28 15  3]
 [ 4  0 20  4  2 20 22  6]]


In [17]:
A = np.array([[1, 0, 3, 7], [1, 0, 4, 2], [1, 0, 6, 2], [1, 0, 3, 2]])
B = np.array([[1, 0, 3, 7], [1, 0, 4, 2], [1, 0, 6, 2], [1, 0, 3, 2]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[1 0 3 7]
 [1 0 4 2]
 [1 0 6 2]
 [1 0 3 2]]
Матрица B
[[1 0 3 7]
 [1 0 4 2]
 [1 0 6 2]
 [1 0 3 2]]
Матрица AB
[[11  0 42 27]
 [ 7  0 33 19]
 [ 9  0 45 23]
 [ 6  0 27 17]]


In [19]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица A+B\n{A+B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица A+B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


In [23]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица C\n{C}')
print(f'Матрица 3A-2B+4C\n{3*A-2*B+4*C}')

Матрица A
[[ 1  7]
 [ 3 -6]]
Матрица B
[[ 0  5]
 [ 2 -1]]
Матрица C
[[ 2 -4]
 [ 1  1]]
Матрица 3A-2B+4C
[[ 11  -5]
 [  9 -12]]


In [27]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица A\n{A}')
print(f'Матрица A.T\n{A.T}')
print(f'Матрица A*A.T\n{np.dot(A,A.T)}')
print(f'Матрица A.T*A\n{np.dot(A.T, A)}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Матрица A.T
[[ 4  5  2]
 [ 1 -2  3]]
Матрица A*A.T
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A.T*A
[[45  0]
 [ 0 14]]


5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [48]:
m2 = [[4,5,2], [1,-2,3]]
m1 = [[4,1],[5,-2],[2, 3]]

if len(m2) != len(m1[0]):
    print("Матрицы не могут быть перемножены")
else:
    m3 = []
    r1 = len(m1) #количество строк в первой матрице
    c1 = len(m1[0]) #Количество столбцов в первой матрице
    r2 = c1  #количество строк во 2ой матрице
    c2 = len(m2[0]) #количество столбцов во 2ой матрице
    for z in range(0,r1):
        t = []
        for j in range(0,c2):
            s = 0
            for i in range(0,c1):
                s=s+m1[z][i]*m2[i][j]
            t.append(s)
            s = 0
        m3.append(t)
print(m3)

[[17, 18, 11], [18, 29, 4], [11, 4, 13]]


### Матрицы и матричные операции. Часть 2

In [49]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


In [50]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


In [51]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


In [52]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [53]:
a = np.array([[0,0,2,1], [0,0,2,2], [0,0,4,3], [2,3,5,6]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
