5*. Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [18]:
import numpy as np

#Минор
def submatrix(M,c):
    B = [[1]*len(M) for i in range(len(M))]
    for l in range(len(M)):
        for k in range(len(M)):
            B[l][k] = M[l][k]
    
    B.pop(0)
    
    for i in range(len(B)):
        B[i].pop(c)
    return B

#Определитель методом Лапласа
def det_L(M):
    X = 0
    if len(M) != len(M[0]):
        print('Матрица не квадратная')
    else:
        if len(M)<=2:
            return M[0][0] * M[1][1] - M[0][1] * M[1][0]
        else:
            for i in range(len(M)):
                X = X + ((-1)**i)*M[0][i]*det_L(submatrix(M,i))
        return X

#Решение методом Крамера
def Kramer(A,B):
    det_A = det_L(A)
    X = []
    if det_A == 0:
        print('Определитель матрицы не должен быть равен 0')
        return X
    n = len(A)    
    for i in range(n):
        matrix = A.copy()
        matrix[:,i] = B
        print('\n',matrix)
        X.append(det_L(matrix) / det_A)
    return X
    
#a = np.random.rand(3,3)
#b = np.random.rand(1,3)
a = np.array([[1,-2],[3,-4]])
b = np.array([1,7])
print(a)
print('\n',b)
print('\n', det_L(a))
print('\n', Kramer(a,b))

[[ 1 -2]
 [ 3 -4]]

 [1 7]

 2

 [[ 1 -2]
 [ 7 -4]]

 [[1 1]
 [3 7]]

 [5.0, 2.0]
